name: "Deploy Fly.io Test App"
description: "Creates and deploys a Fly.io app with volume and secrets for testing"

inputs:
  app-name:
    description: "Fly.io app name"
    required: true
  region:
    description: "Fly.io region"
    required: false
    default: "sjc"
  volume-name:
    description: "Volume name"
    required: false
    default: "test_data"
  volume-size:
    description: "Volume size in GB"
    required: false
    default: "20"
  ssh-pubkey-path:
    description: "Path to SSH public key file"
    required: false
    default: "test_key.pub"
  fly-api-token:
    description: "Fly.io API token"
    required: true
  org:
    description: "Fly.io organization"
    required: false
    default: "personal"
  max-deploy-attempts:
    description: "Maximum deployment retry attempts"
    required: false
    default: "3"
  deploy-timeout:
    description: "Deployment timeout in seconds"
    required: false
    default: "300"
  pre-built-image:
    description: "Pre-built Docker image URL (e.g., registry.fly.io/app:tag). If provided, skips build."
    required: false
    default: ""
  anthropic-api-key:
    description: "Anthropic API key for Claude authentication (optional, enables plugin installation)"
    required: false
    default: ""
  ci-mode:
    description: "Enable CI mode (uses CI manifest, skips heavy installations). Default: false for production safety."
    required: false
    default: "false"

outputs:
  deployment-status:
    description: "Deployment status (success or failure)"
    value: ${{ steps.deploy.outputs.status }}

runs:
  using: "composite"
  steps:
    # SECURITY: Mask secrets to prevent disclosure in logs (C8 fix)
    - name: Mask secrets
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-api-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
      run: |
        set +x  # Disable command echoing
        # Mask FLY_API_TOKEN if present
        if [[ -n "$FLY_API_TOKEN" ]]; then
          echo "::add-mask::${FLY_API_TOKEN}"
        fi
        # Mask ANTHROPIC_API_KEY if present
        if [[ -n "$ANTHROPIC_API_KEY" ]]; then
          echo "::add-mask::${ANTHROPIC_API_KEY}"
        fi
        echo "✓ Secrets masked"

    - name: Create Fly.io app
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-api-token }}
      run: |
        set +x  # Disable command echoing
        echo "Creating Fly.io app: ${{ inputs.app-name }}"
        flyctl apps create ${{ inputs.app-name }} --org ${{ inputs.org }} || echo "App may already exist"

    - name: Wait for app readiness (Fly.io eventual consistency)
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-api-token }}
      run: |
        echo "Waiting for app to propagate across Fly.io API endpoints..."
        max_attempts=10
        attempt=1

        while [ $attempt -le $max_attempts ]; do
          echo "Checking app availability (attempt $attempt/$max_attempts)..."

          if flyctl status --app ${{ inputs.app-name }} &>/dev/null; then
            echo "✅ App is ready and propagated"
            break
          else
            if [ $attempt -lt $max_attempts ]; then
              wait_time=$((2 * attempt))  # Linear backoff: 2, 4, 6, 8... seconds
              echo "⚠️  App not yet available, waiting ${wait_time}s..."
              sleep $wait_time
              attempt=$((attempt + 1))
            else
              echo "❌ App not available after $max_attempts attempts"
              exit 1
            fi
          fi
        done

    - name: Create volume
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-api-token }}
      run: |
        echo "Creating volume: ${{ inputs.volume-name }}"
        max_attempts=5
        attempt=1

        while [ $attempt -le $max_attempts ]; do
          echo "Volume creation attempt $attempt/$max_attempts..."

          if flyctl volumes create ${{ inputs.volume-name }} \
            --app ${{ inputs.app-name }} \
            --region ${{ inputs.region }} \
            --size ${{ inputs.volume-size }} \
            --no-encryption \
            --yes; then
            echo "✅ Volume created successfully"
            break
          else
            if [ $attempt -lt $max_attempts ]; then
              wait_time=$((2 * attempt))
              echo "⚠️  Volume creation failed, retrying in ${wait_time}s..."
              sleep $wait_time
              attempt=$((attempt + 1))
            else
              echo "❌ Volume creation failed after $max_attempts attempts"
              exit 1
            fi
          fi
        done

    - name: Prepare fly.toml configuration
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-api-token }}
      run: |
        echo "Preparing fly.toml configuration..."
        # Set required environment variables for prepare-fly-config.sh
        export APP_NAME="${{ inputs.app-name }}"
        export REGION="${{ inputs.region }}"
        export VOLUME_NAME="${{ inputs.volume-name }}"
        export VOLUME_SIZE="${{ inputs.volume-size }}"

        # Prepare the configuration with CI mode if needed
        if [ "${{ inputs.ci-mode }}" = "true" ]; then
          echo "Preparing fly.toml with CI mode (health checks disabled)..."
          ./scripts/prepare-fly-config.sh --ci-mode
        else
          echo "Preparing fly.toml for production mode..."
          ./scripts/prepare-fly-config.sh
        fi

        echo "✓ fly.toml prepared"

    - name: Set secrets
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-api-token }}
      run: |
        echo "Setting secrets for app: ${{ inputs.app-name }}"

        # Helper function to set secrets with retry logic
        set_secret_with_retry() {
          local secret_name=$1
          local secret_value=$2
          local max_attempts=5
          local attempt=1

          while [ $attempt -le $max_attempts ]; do
            echo "Setting ${secret_name} (attempt $attempt/$max_attempts)..."

            if flyctl secrets set "${secret_name}=${secret_value}" --app ${{ inputs.app-name }}; then
              echo "✅ ${secret_name} set successfully"
              return 0
            else
              if [ $attempt -lt $max_attempts ]; then
                wait_time=$((2 * attempt))
                echo "⚠️  Failed to set ${secret_name}, retrying in ${wait_time}s..."
                sleep $wait_time
                attempt=$((attempt + 1))
              else
                echo "❌ Failed to set ${secret_name} after $max_attempts attempts"
                return 1
              fi
            fi
          done
        }

        # Set SSH authorized keys
        ssh_key_content=$(cat ${{ inputs.ssh-pubkey-path }})
        set_secret_with_retry "AUTHORIZED_KEYS" "$ssh_key_content" || exit 1

        # Set CI_MODE if explicitly enabled (default: false for production safety)
        if [ "${{ inputs.ci-mode }}" = "true" ]; then
          echo "Setting CI_MODE=true for test environment..."
          set_secret_with_retry "CI_MODE" "true" || exit 1
          echo "✓ CI mode enabled"
        else
          echo "Note: CI mode disabled (production mode) - full installations will be used"
        fi

        # Set ANTHROPIC_API_KEY if provided (required for claude-marketplace plugin installation)
        if [ -n "${{ inputs.anthropic-api-key }}" ]; then
          echo "Setting ANTHROPIC_API_KEY for Claude authentication..."
          set_secret_with_retry "ANTHROPIC_API_KEY" "${{ inputs.anthropic-api-key }}" || exit 1
          echo "✓ Claude authentication enabled"
        else
          echo "Note: ANTHROPIC_API_KEY not provided - claude/claude-marketplace will have limited functionality"
        fi

    - name: Deploy app with retry logic
      id: deploy
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-api-token }}
      run: |
        echo "Deploying app: ${{ inputs.app-name }}"
        max_attempts=${{ inputs.max-deploy-attempts }}
        attempt=1

        # Determine deployment command
        if [ -n "${{ inputs.pre-built-image }}" ]; then
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Using pre-built image (fast deployment)"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Image: ${{ inputs.pre-built-image }}"
          echo ""

          DEPLOY_CMD="flyctl deploy --app ${{ inputs.app-name }} \
            --image ${{ inputs.pre-built-image }} \
            --strategy immediate \
            --wait-timeout ${{ inputs.deploy-timeout }}s \
            --yes"
        else
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Building from source (no pre-built image)"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo ""

          DEPLOY_CMD="flyctl deploy --app ${{ inputs.app-name }} \
            --strategy immediate \
            --wait-timeout ${{ inputs.deploy-timeout }}s \
            --yes"
        fi

        while [ $attempt -le $max_attempts ]; do
          echo "Deployment attempt $attempt of $max_attempts..."

          if eval $DEPLOY_CMD; then
            echo "✅ Deployment successful"
            echo "status=success" >> $GITHUB_OUTPUT
            exit 0
          else
            if [ $attempt -lt $max_attempts ]; then
              wait_time=$((30 * attempt))
              echo "⚠️  Deployment failed, retrying in ${wait_time}s..."
              sleep $wait_time
              attempt=$((attempt + 1))
            else
              echo "❌ Deployment failed after $max_attempts attempts"
              echo "status=failure" >> $GITHUB_OUTPUT
              exit 1
            fi
          fi
        done
