name: "Setup Fly.io Test Environment"
description: "Prepares environment for Fly.io extension testing (checkout, Fly CLI, SSH keys, app naming)"

inputs:
  app-prefix:
    description: 'Prefix for test app name (e.g., "ext-test")'
    required: true
  extension-name:
    description: "Extension name for app naming (will be sanitized)"
    required: false
    default: "generic"
  fly-api-token:
    description: "Fly.io API token"
    required: true
  vm-memory:
    description: "VM memory in MB"
    required: false
    default: "8192"
  vm-cpu-kind:
    description: "CPU kind (performance or shared)"
    required: false
    default: "performance"
  vm-cpu-count:
    description: "Number of CPUs"
    required: false
    default: "4"
  volume-name:
    description: "Volume name"
    required: false
    default: "test_data"
  volume-size:
    description: "Volume size in GB"
    required: false
    default: "20"

outputs:
  app-name:
    description: "Generated app name for testing"
    value: ${{ steps.generate-app-name.outputs.app_name }}
  ssh-key-path:
    description: "Path to generated SSH private key"
    value: "test_key"
  ssh-pubkey-path:
    description: "Path to generated SSH public key"
    value: "test_key.pub"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Generate test app name
      id: generate-app-name
      shell: bash
      run: |
        timestamp=$(date +%s)
        # Sanitize extension name to avoid Fly.io abuse filter (e.g., "github" -> "gh")
        extension_name="${{ inputs.extension-name }}"
        extension_name="${extension_name//github/gh}"
        app_name="${{ inputs.app-prefix }}-${extension_name}-${timestamp}"
        echo "app_name=$app_name" >> $GITHUB_OUTPUT
        echo "Generated test app name: $app_name"

    - name: Create test SSH key
      shell: bash
      run: |
        ssh-keygen -t ed25519 -f test_key -N "" -C "ext-test"
        chmod 600 test_key
        chmod 644 test_key.pub
        echo "✅ SSH key pair created"

    - name: Prepare fly.toml for testing
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-api-token }}
        APP_NAME: ${{ steps.generate-app-name.outputs.app_name }}
        VOLUME_NAME: ${{ inputs.volume-name }}
        VOLUME_SIZE: ${{ inputs.volume-size }}
        VM_MEMORY: ${{ inputs.vm-memory }}
        CPU_KIND: ${{ inputs.vm-cpu-kind }}
        CPU_COUNT: ${{ inputs.vm-cpu-count }}
        CI_MODE: "true"
      run: |
        ./scripts/prepare-fly-config.sh --ci-mode
        echo "✅ fly.toml prepared for testing"
