#!/bin/bash
#
# project-core.sh - Core project operations shared by new-project and clone-project
#
# This library provides shared functionality for project creation and repository
# cloning operations, including dependency installation, Claude tools initialization,
# Git configuration, and project enhancement orchestration.
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"
source "${SCRIPT_DIR}/git.sh"

# shellcheck disable=SC2120
install_project_dependencies() {
    local skip_build=false
    [[ "$1" == "--skip-build" ]] && skip_build=true

    print_status "Detecting and installing project dependencies..."

    local deps_installed=false

    if [[ -f "package.json" ]] && command_exists npm; then
        print_status "Installing Node.js dependencies..."
        if npm install; then
            deps_installed=true
            print_success "Node.js dependencies installed"
        else
            print_error "Failed to install Node.js dependencies"
            return 1
        fi
    fi

    if [[ -f "requirements.txt" ]] && command_exists pip3; then
        print_status "Installing Python dependencies..."
        if pip3 install -r requirements.txt; then
            deps_installed=true
            print_success "Python dependencies installed"
        else
            print_error "Failed to install Python dependencies"
            return 1
        fi
    fi

    if [[ -f "go.mod" ]] && command_exists go; then
        print_status "Installing Go dependencies..."
        if go mod download; then
            deps_installed=true
            print_success "Go dependencies installed"
        else
            print_error "Failed to install Go dependencies"
            return 1
        fi
    fi

    if [[ -f "Cargo.toml" ]] && command_exists cargo; then
        if [[ "$skip_build" == "false" ]]; then
            print_status "Building Rust project..."
            if cargo build; then
                deps_installed=true
                print_success "Rust project built"
            else
                print_error "Failed to build Rust project"
                return 1
            fi
        else
            print_status "Fetching Rust dependencies..."
            if cargo fetch; then
                deps_installed=true
                print_success "Rust dependencies fetched"
            else
                print_error "Failed to fetch Rust dependencies"
                return 1
            fi
        fi
    fi

    if [[ -f "Gemfile" ]] && command_exists bundle; then
        print_status "Installing Ruby dependencies..."
        if bundle install; then
            deps_installed=true
            print_success "Ruby dependencies installed"
        else
            print_error "Failed to install Ruby dependencies"
            return 1
        fi
    fi

    [[ "$deps_installed" == "false" ]] && print_debug "No dependency files detected"
    return 0
}

init_claude_tools() {
    local tools_initialized=false

    if command_exists uvx || command_exists uv; then
        print_status "Initializing GitHub spec-kit..."
        if uvx --from git+https://github.com/github/spec-kit.git specify init --here 2>/dev/null; then
            print_success "GitHub spec-kit initialized"
            tools_initialized=true

            if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
                git add . 2>/dev/null
                git commit -m "feat: add GitHub spec-kit configuration" 2>/dev/null || true
            fi
        else
            print_debug "GitHub spec-kit initialization skipped"
        fi
    fi

    if command_exists npx; then
        print_status "Initializing Claude Flow..."
        if npx claude-flow@alpha init --force 2>/dev/null; then
            print_success "Claude Flow initialized"
            tools_initialized=true
        else
            print_debug "Claude Flow initialization skipped"
        fi
    else
        print_debug "Skipping Claude Flow initialization (npx not available)"
    fi

    if command_exists npx; then
        print_status "Checking agent-flow availability..."
        if npx --yes agentic-flow --help >/dev/null 2>&1; then
            print_success "agent-flow available"
            tools_initialized=true
        else
            print_debug "agent-flow initialization skipped"
        fi
    fi

    if [[ "$tools_initialized" == "true" ]]; then
        print_status "Creating .envrc for direnv integration..."
        cat > .envrc << 'ENVRC_EOF'
# Auto-generated by Sindri project setup
# This file enables project-specific Claude Flow and Agentic Flow aliases

# Load Claude Flow aliases if initialized
if [[ -d .swarm ]] || command -v npx >/dev/null 2>&1; then
    [[ -f /workspace/config/claude-flow.aliases ]] && source /workspace/config/claude-flow.aliases
fi

# Load Agentic Flow aliases if available
if command -v npx >/dev/null 2>&1 && npx --yes agentic-flow --help >/dev/null 2>&1; then
    [[ -f /workspace/config/agentic-flow.aliases ]] && source /workspace/config/agentic-flow.aliases
fi
ENVRC_EOF

        if command_exists direnv; then
            direnv allow . >/dev/null 2>&1 || true
            print_success ".envrc created and allowed"
        else
            print_success ".envrc created (direnv will auto-load on next shell)"
        fi
    fi

    [[ "$tools_initialized" == "false" ]] && print_warning "No Claude tools were initialized"
    return 0
}

apply_git_config_overrides() {
    local git_name=""
    local git_email=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --name)
                git_name="$2"
                shift 2
                ;;
            --email)
                git_email="$2"
                shift 2
                ;;
            *)
                print_error "Unknown option: $1"
                return 1
                ;;
        esac
    done

    if [[ -z "$git_name" ]] && [[ -z "$git_email" ]]; then
        print_debug "No Git config overrides to apply"
        return 0
    fi

    print_status "Configuring Git for this project..."

    if [[ -n "$git_name" ]]; then
        if git config user.name "$git_name"; then
            print_success "Git user name set to: $git_name"
        else
            print_error "Failed to set Git user name"
            return 1
        fi
    fi

    if [[ -n "$git_email" ]]; then
        if git config user.email "$git_email"; then
            print_success "Git user email set to: $git_email"
        else
            print_error "Failed to set Git user email"
            return 1
        fi
    fi

    return 0
}

create_project_claude_md() {
    local template_content=""
    local use_cli=false

    while [[ $# -gt 0 ]]; do
        case $1 in
            --template)
                template_content="$2"
                shift 2
                ;;
            --from-cli)
                use_cli=true
                shift
                ;;
            *)
                print_error "Unknown option: $1"
                return 1
                ;;
        esac
    done

    if [[ -f "CLAUDE.md" ]]; then
        print_success "CLAUDE.md already exists"
        return 0
    fi

    print_status "Creating CLAUDE.md..."

    if [[ "$use_cli" == "true" ]] && command_exists claude; then
        if claude /init 2>/dev/null; then
            print_success "CLAUDE.md created via claude CLI"
            return 0
        fi
    fi

    if [[ -n "$template_content" ]]; then
        echo "$template_content" > CLAUDE.md
        print_success "CLAUDE.md created from template"
        return 0
    fi

    local project_name
    project_name=$(basename "$(pwd)")

    cat > CLAUDE.md << EOF
# ${project_name}

## Project Overview
This project was created with Sindri.

## Setup Instructions
[Add setup instructions here]

## Development Commands
[Add common commands here]

## Architecture Notes
[Add architectural decisions and patterns]

## Important Files
[List key files and their purposes]
EOF

    print_success "CLAUDE.md created with basic template"
    return 0
}

setup_project_enhancements() {
    local skip_deps=false
    local skip_tools=false
    local git_name=""
    local git_email=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --skip-deps)
                skip_deps=true
                shift
                ;;
            --skip-claude-tools)
                skip_tools=true
                shift
                ;;
            --git-name)
                git_name="$2"
                shift 2
                ;;
            --git-email)
                git_email="$2"
                shift 2
                ;;
            *)
                print_error "Unknown option: $1"
                return 1
                ;;
        esac
    done

    print_status "Setting up project enhancements..."

    if [[ -n "$git_name" ]] || [[ -n "$git_email" ]]; then
        apply_git_config_overrides ${git_name:+--name "$git_name"} ${git_email:+--email "$git_email"} || return 1
    fi

    if [[ "$skip_deps" == "false" ]]; then
        # shellcheck disable=SC2119
        install_project_dependencies || print_warning "Dependency installation failed, continuing..."
    fi

    if [[ "$skip_tools" == "false" ]]; then
        init_claude_tools || print_warning "Claude tools initialization failed, continuing..."
    fi

    print_success "Project enhancements complete"
    return 0
}

export -f install_project_dependencies
export -f init_claude_tools
export -f apply_git_config_overrides
export -f create_project_claude_md
export -f setup_project_enhancements
